function [plan,manifest] = sensitivity_design(cfg,recordFile,recordSHA256,archive)
%SENSITIVITY_DESIGN Declare the unchanged paired sensitivity cases without reading data.
% ARCHIVE identifies optional reference metadata; generation never reads it.
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
plan = struct('root',root,'cfg',cfg,'recordFile',recordFile, ...
    'recordSHA256',recordSHA256,'archive',archive);
plan.analysisSeed = 7401; plan.bootstrapCount = 2000;
plan.configurations = table(["baseline";"R_half";"R_double";"prior_tenth";"prior_tenfold";"fit_50";"fit_100"], ...
    [.05;.025;.10;.05;.05;.05;.05],[1;1;1;.1;10;1;1],[200;200;200;200;200;50;100], ...
    'VariableNames',{'configuration','R','alphaP','fittingTransitions'});
plan.modelIds = ["A","S","W","R","P2","K"];
plan.modelNames = ["Affine","Shared","Incorrectly shared","Relaxed","Complete quadratic","Known-model reference"];
plan.cachePolicy = 'No fit-state cache: fit fresh from the paired prefix for every adaptive run';
plan.scaling = 'Fixed 41-by-41 grid [-1.2,1.2] x [-1,1]; rowScale=1; beta=D.*theta';
rows = struct([]);
for ic = 1:7
    c = plan.configurations(ic,:);
    for im = 1:6
        known = im == 6;
        if known && ic > 3, continue; end
        for trial = 0:40
            alpha = c.alphaP; length = c.fittingTransitions; n = [3 3 3 4 6 0];
            if known, alpha = NaN; length = NaN; end
            runId = sprintf('%s_%s_%03d',c.configuration,plan.modelIds(im),trial);
            initialNoise = NaN; controlNoise = NaN;
            if trial > 0, initialNoise = 2200+trial; controlNoise = 2300+trial; end
            if known, initialNoise = NaN; end
            baseline = fullfile(plan.archive,'data',sprintf('confirmation_%s_%03d.mat',plan.modelIds(im),trial));
            row = struct('runId',string(runId),'configuration',c.configuration, ...
                'modelId',plan.modelIds(im),'model',plan.modelNames(im),'nTheta',n(im), ...
                'trial',trial,'noisy',trial>0,'R',c.R,'alphaP',alpha, ...
                'fittingTransitions',length,'identificationApplicable',~known, ...
                'Ts',cfg.Ts,'durationSeconds',cfg.duration,'controlInstants',cfg.K, ...
                'trackingWindow',"[0,120)",'incrementIndices',"k=1:1199", ...
                'initialInputSeed',2101,'evaluationInputSeed',2102, ...
                'initialNoiseSeed',initialNoise,'controlNoiseSeed',controlNoise, ...
                'recordFile',string(plan.recordFile),'recordSHA256',string(plan.recordSHA256), ...
                'recordCampaignLabel',"confirmation",'scientificStatus',"paired P06 sensitivity; not independent confirmation", ...
                'baselineFile',string(baseline),'baselineGate',ic==1 && trial<=1, ...
                'dependency',"all 12 baseline-gate cases must pass before non-gate runs", ...
                'executionStatus',"PROPOSED_NOT_RUN");
            rows = [rows;row]; %#ok<AGROW>
        end
    end
end
manifest = struct2table(rows);
plan.knownAliases = table(plan.configurations.configuration, ...
    ["baseline";"R_half";"R_double";"baseline";"baseline";"baseline";"baseline"], ...
    'VariableNames',{'requestedConfiguration','knownReferenceConfiguration'});
plan.proposedRunCount = height(manifest);
assert(height(manifest)==1558 && nnz(~manifest.noisy)==38 && nnz(manifest.baselineGate)==12);
end
