function [plan,manifest] = sensitivity_plan
%SENSITIVITY_PLAN Check reference identities and declare the fixed 1,558-case design.
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
plan.root = root;
plan.archive = fullfile(root,'references','study1');
plan.recordFile = fullfile(plan.archive,'data','records_confirmation.mat');
plan.settingsFile = fullfile(plan.archive,'settings.mat');
s = load(plan.settingsFile,'cfg','environment');
r = load(plan.recordFile,'records'); r = r.records;
cfg = study1_settings;
assert(isequaln(cfg,s.cfg),'p06:BaselineSettings','Current and saved Study 1 settings differ.');
assert(cfg.Ts == .1 && cfg.K == 1200 && cfg.duration == 120 && cfg.N == 10 ...
    && cfg.control.R == .05 && cfg.noiseSigma == .01,'p06:Baseline','Unexpected baseline.');
assert(isequal(cfg.confirmation,struct('inputSeed',2101,'evaluationSeed',2102, ...
    'initialNoiseBase',2200,'controlNoiseBase',2300,'bootstrapSeed',2401,'noiseTrials',40)), ...
    'p06:Seeds','Saved pairing differs from the approved specification.');
assert(strcmp(r.campaign,'confirmation') && r.initialization.seed == 2101 ...
    && r.evaluation.seed == 2102 && r.initialization.L == .5 && r.evaluation.L == .5, ...
    'p06:RecordIdentity','Unexpected saved record identity.');
assert(isequal(size(r.initialization.u),[1 200]) && isequal(size(r.initialization.x),[1 201]) ...
    && isequal(size(r.evaluation.u),[1 600]) && isequal(size(r.evaluation.x),[1 601]) ...
    && isequal(size(r.initialNoise),[40 201]) && isequal(size(r.controlNoise),[40 1201]), ...
    'p06:RecordShape','Saved record dimensions differ.');
assert(isequal(r.initialization.y,r.initialization.x) && isequal(r.evaluation.y,r.evaluation.x), ...
    'p06:CleanRecords','Saved common records must be noise-free.');
plan.cfg = cfg; plan.historicalEnvironment = s.environment;
plan.recordSHA256 = sensitivity_hash(plan.recordFile);
plan.settingsSHA256 = sensitivity_hash(plan.settingsFile);
plan.generator = 'mt19937ar (current study1_prepare/record source); stored arrays reused without regeneration';
plan.analysisSeed = 7401; plan.bootstrapCount = 2000;
plan.configurations = table(["baseline";"R_half";"R_double";"prior_tenth";"prior_tenfold";"fit_50";"fit_100"], ...
    [.05;.025;.10;.05;.05;.05;.05],[1;1;1;.1;10;1;1],[200;200;200;200;200;50;100], ...
    'VariableNames',{'configuration','R','alphaP','fittingTransitions'});
plan.modelIds = ["A","S","W","R","P2","K"];
plan.modelNames = ["Affine","Shared","Incorrectly shared","Relaxed","Complete quadratic","Known-model reference"];
plan.cachePolicy = 'No fit-state cache: fit fresh from the paired prefix for every adaptive run';
plan.scaling = 'Fixed 41-by-41 grid [-1.2,1.2] x [-1,1]; rowScale=1; beta=D.*theta';
% Record the algorithm and interface file identities used by the design.
sourceFiles = [dir(fullfile(root,'src','*.m'));dir(fullfile(root,'studies','study1','*.m')); ...
    dir(fullfile(root,'*.m'))];
plan.sources = struct('file',{},'sha256',{});
for j = 1:numel(sourceFiles)
    p = fullfile(sourceFiles(j).folder,sourceFiles(j).name);
    plan.sources(j) = struct('file',p,'sha256',sensitivity_hash(p));
end
rows = struct([]);
for ic = 1:7
    c = plan.configurations(ic,:);
    for im = 1:6
        known = im == 6;
        if known && ic > 3, continue; end
        for trial = 0:40
            alpha = c.alphaP; length = c.fittingTransitions; n = [3 3 3 4 6 0];
            if known, alpha = NaN; length = NaN; end
            runId = sprintf('%s_%s_%03d',c.configuration,plan.modelIds(im),trial);
            initialNoise = NaN; controlNoise = NaN;
            if trial > 0, initialNoise = 2200+trial; controlNoise = 2300+trial; end
            if known, initialNoise = NaN; end
            baseline = fullfile(plan.archive,'data',sprintf('confirmation_%s_%03d.mat',plan.modelIds(im),trial));
            assert(isfile(baseline),'p06:MissingBaseline','Missing baseline %s.',baseline);
            row = struct('runId',string(runId),'configuration',c.configuration, ...
                'modelId',plan.modelIds(im),'model',plan.modelNames(im),'nTheta',n(im), ...
                'trial',trial,'noisy',trial>0,'R',c.R,'alphaP',alpha, ...
                'fittingTransitions',length,'identificationApplicable',~known, ...
                'Ts',cfg.Ts,'durationSeconds',cfg.duration,'controlInstants',cfg.K, ...
                'trackingWindow',"[0,120)",'incrementIndices',"k=1:1199", ...
                'initialInputSeed',2101,'evaluationInputSeed',2102, ...
                'initialNoiseSeed',initialNoise,'controlNoiseSeed',controlNoise, ...
                'recordFile',string(plan.recordFile),'recordSHA256',string(plan.recordSHA256), ...
                'recordCampaignLabel',"confirmation",'scientificStatus',"paired P06 sensitivity; not independent confirmation", ...
                'baselineFile',string(baseline),'baselineGate',ic==1 && trial<=1, ...
                'dependency',"all 12 baseline-gate cases must pass before non-gate runs", ...
                'executionStatus',"PROPOSED_NOT_RUN");
            rows = [rows;row]; %#ok<AGROW>
        end
    end
end
manifest = struct2table(rows);
plan.knownAliases = table(plan.configurations.configuration, ...
    ["baseline";"R_half";"R_double";"baseline";"baseline";"baseline";"baseline"], ...
    'VariableNames',{'requestedConfiguration','knownReferenceConfiguration'});
plan.proposedRunCount = height(manifest);
assert(height(manifest)==1558 && nnz(~manifest.noisy)==38 && nnz(manifest.baselineGate)==12);
end
