function schema = p06_schema
%P06_SCHEMA Definitions only; this function creates no numerical result.
rows={ ...
 'runs','runId/configuration/modelId/model/trial','Exact proposed identity and descriptive model name','identifier','All attempts'; ...
 'runs','R/alphaP/fittingTransitions/nTheta','OFAT settings; alphaP/length NaN for known-model reference','normalized units/count','Known identification fields N/A'; ...
 'runs','recordFile/recordSHA256/initialInputSeed/evaluationInputSeed/initialNoiseSeed/controlNoiseSeed','Immutable paired record and declared stream identities','identifier','No regenerated arrays'; ...
 'runs','executionStatus','COMPLETED, TERMINATED, or FAILED_SETUP_OR_EXECUTION','category','PROPOSED_NOT_RUN appears only in manifest'; ...
 'runs','completed/nSteps','Full 1200-step completion and number of completed transitions','logical/count','Never score an incomplete prefix as a complete run'; ...
 'runs','predictionCompleted','All 600 held-out one-step queries finite after selected fit','logical','Separate from later control completion'; ...
 'runs','predictionRMS','study1 score_fit: sqrt(mean(oneStepErrors.^2)) on independent 600-transition record','dimensionless state','NaN for undefined score; no evaluation refit'; ...
 'runs','trackingRMS','study1 score_run whole window: true x(k)-r(k), k=0:1199','dimensionless state','NaN in this table unless completed'; ...
 'runs','inputRMS','study1 score_run whole window: applied u(k), k=0:1199','dimensionless input','Unused terminal input excluded'; ...
 'runs','meanAbsoluteIncrement','study1 score_run: mean abs(u(k)-u(k-1)), k=1:1199','input units per sample','NaN unless completed'; ...
 'runs','identificationRejected/initializationRejected/controlRejected','Counts from unchanged study1 diagnose_run','count','NaN if no result was returned'; ...
 'runs','outputViolationPeak/inputViolationPeak/incrementViolationPeak','Unchanged whole-window study1 score_run exceedances','state/input units','Partial-scope peaks on terminated runs; status explicit'; ...
 'runs','failureMessage','Recorded termination or thrown exception message','text','Empty on ordinary completion'; ...
 'runs/*.mat','result','Full existing study1_trajectory log with theta, covariance, x/y/u, events, plans, residuals and timing','Study 1 units','No full QP Hessian added'; ...
 'runs/*.mat','result.fit','Selected-prefix fit histories including raw theta0, normalized P0, D and final beta/P','scaled parameter coordinates','Prior multiplier applied before fitting'; ...
 'runs/*.mat','result.forecasts','Existing oneStepErrors; anchors empty so no extra multistep queries','dimensionless state','600 queries; chosen fit only'; ...
 'runs/*.mat','scores.metrics','Original whole and stationary rows, including explicitly labelled finite prefixes','Study 1 units','Stationary windows include reference preview'; ...
 'runs/*.mat','scores.diagnostics','Original rejection/fallback/bound/condition/residual/timing summaries','field-dependent','Raw Gram cond(G), not corrected Eq. A.7'; ...
 'runs/*.mat','scores.initialization','Original score_fit prediction/counts; no new performance index','Study 1 units','Exact parameter targets only where Study 1 supplies them'; ...
 'runs/*.mat','failure','Exception identifier, message and stack if execution failed','text','Never silently drop attempted run'; ...
 'noisy_summaries','attempted/completedControl/terminatedOrFailed/eligibleScores/finiteScores','Full attempted denominator and explicitly conditional score counts','count','40 noisy trials per distinct model/configuration'; ...
 'noisy_summaries','median/q1/q3/iqr','Existing percentile helper at positions 1+(n-1)*p','metric units','Conditional eligible set; NaN if nonfinite eligible score'; ...
 'paired_contrasts','left/right/metric/signConvention','Left minus right; sorted trial-ID pairing','identifier','Within-config model contrasts then within-model sensitivity'; ...
 'paired_contrasts','attemptedPairs/completePairs/finitePairs','Matched trial counts, eligibility and finite differences','count','Failed attempts remain in denominator'; ...
 'paired_contrasts','medianDifference/lower95/upper95','Paired median and 2000-resample percentile endpoints; P06 seed 7401','dimensionless state','Contrast-specific 95%; not simultaneous'; ...
 'analysis_randomness.mat','analysis','mt19937ar seed, initial state, pre-contrast states, final state','RNG state','Separate from immutable plant/noise streams'; ...
 'baseline_gate','quantity/absoluteTolerance/relativeTolerance/maxAbsoluteDifference/passed','Predeclared equality checks against saved nominal cases','quantity-dependent','Mismatch stops remaining campaign'; ...
 'known_reference_aliases','requestedConfiguration/knownReferenceConfiguration','Prior/length variants map to existing R=.05 reference','identifier','No duplicated observations'; ...
 'execution_provenance.mat','provenance/plan','Actual source hashes, source snapshot, environment/options, records and design','metadata','Does not establish historical provenance or confirmation'};
schema=cell2table(rows,'VariableNames',{'artifact','columnsOrVariables','definition','units','statusConvention'});
end
