function info = p06_provenance(plan)
%P06_PROVENANCE Current source/environment are not historical run provenance.
[status,head] = system(sprintf('git -c safe.directory="%s" -C "%s" rev-parse HEAD',plan.root,plan.root));
assert(status==0,'p06:Git','Cannot identify current base commit.');
[status,dirty] = system(sprintf('git -c safe.directory="%s" -C "%s" status --porcelain=v1',plan.root,plan.root));
assert(status==0,'p06:Git','Cannot identify working-tree state.');
info = struct('baseCommit',strtrim(head),'workingTree',dirty,'MATLAB',version, ...
    'computer',computer,'toolboxes',ver,'quadprogPath',which('quadprog'), ...
    'optimizationLicenseAvailable',license('test','Optimization_Toolbox'), ...
    'historicalProducingCommit','UNKNOWN','historicalDirtyState','UNKNOWN', ...
    'historicalOSVersion','UNKNOWN','historicalSolverOptions','UNKNOWN', ...
    'historicalSavedEnvironment',plan.historicalEnvironment,'recordFile',plan.recordFile, ...
    'recordSHA256',plan.recordSHA256,'settingsSHA256',plan.settingsSHA256, ...
    'generator',plan.generator,'sources',plan.sources,'productionLaunched',false, ...
    'P06','UNRESOLVED','P07','UNRESOLVED','P08','UNRESOLVED');
info.solver = struct('algorithm','interior-point-convex','Display','off', ...
    'ConstraintTolerance',1e-8,'OptimalityTolerance',1e-8, ...
    'normalizedKKTRejectionThreshold',1e-7,'positiveExitflagRequired',true);
if ~isempty(which('quadprog'))
    % Capture all effective defaults as well as the explicit source options.
    options = optimoptions('quadprog','Algorithm','interior-point-convex', ...
        'Display','off','ConstraintTolerance',1e-8,'OptimalityTolerance',1e-8);
    names=properties(options); effective=struct;
    for j=1:numel(names), effective.(names{j})=options.(names{j}); end
    info.solver.effectiveOptions=effective;
end
files=dir(fullfile(fileparts(mfilename('fullpath')),'**','*'));
info.p06Files=struct('file',{},'sha256',{});
for j=1:numel(files)
    if files(j).isdir, continue; end
    file=fullfile(files(j).folder,files(j).name);
    info.p06Files(end+1)=struct('file',file,'sha256',p06_hash(file));
end
end
