function p06_check_records(cfg,r)
%P06_CHECK_RECORDS Preserve the original paired-record requirements.
assert(cfg.Ts == .1 && cfg.K == 1200 && cfg.duration == 120 && cfg.N == 10 ...
    && cfg.control.R == .05 && cfg.noiseSigma == .01,'p06:Baseline','Unexpected baseline.');
assert(isequal(cfg.confirmation,struct('inputSeed',2101,'evaluationSeed',2102, ...
    'initialNoiseBase',2200,'controlNoiseBase',2300,'bootstrapSeed',2401,'noiseTrials',40)), ...
    'p06:Seeds','Saved pairing differs from the approved specification.');
assert(strcmp(r.campaign,'confirmation') && r.initialization.seed == 2101 ...
    && r.evaluation.seed == 2102 && r.initialization.L == .5 && r.evaluation.L == .5, ...
    'p06:RecordIdentity','Unexpected saved record identity.');
assert(isequal(size(r.initialization.u),[1 200]) && isequal(size(r.initialization.x),[1 201]) ...
    && isequal(size(r.evaluation.u),[1 600]) && isequal(size(r.evaluation.x),[1 601]) ...
    && isequal(size(r.initialNoise),[40 201]) && isequal(size(r.controlNoise),[40 1201]), ...
    'p06:RecordShape','Saved record dimensions differ.');
assert(isequal(r.initialization.y,r.initialization.x) && isequal(r.evaluation.y,r.evaluation.x), ...
    'p06:CleanRecords','Saved common records must be noise-free.');
end
