function values = study2_figure_data(resultsDir)
%STUDY2_FIGURE_DATA Select publication scores and check their saved-data provenance.
% This reads saved tables and records only; it performs no fitting or rollout.
learning = readtable(fullfile(resultsDir,'tables','initialization_scores.csv'), ...
    'TextType','string');
tracking = readtable(fullfile(resultsDir,'tables','run_metrics.csv'), ...
    'TextType','string');
saved = load(fullfile(resultsDir,'settings.mat'),'cfg');
cfg = saved.cfg;
assert(isequal(cfg.evaluationRanges,[.25 .70 1.10]) && ...
    isequal(cfg.amplitudes,[.2 .6 1]) && cfg.Ts == .1 && cfg.K == 800, ...
    'study2:FigureProtocol','Unexpected archived experiment settings.');
ids = ["A","E","O3","O5","P3","K"];
names = ["Affine","Exact sine","Odd cubic","Odd quintic","Complete cubic","Known model"];
rows = struct([]);
for j = 1:numel(ids)
    if j < 6
        block = sortrows(learning(learning.model == ids(j) & ...
            learning.fittingTransitions == 200,:),'evaluationRange');
        assert(height(block) == 3 && isequal(block.evaluationRange,[.25;.70;1.10]) && ...
            all(block.evaluationQueries == 600 & block.finiteQueries == 600), ...
            'study2:FigurePredictionData','Expected three complete 200-transition scores.');
        saved = load(fullfile(resultsDir,'fits',[char(ids(j)),'.mat']),'fit');
        fit = saved.fit;
        checkpoint = find(cfg.fitSteps == 200);
        assert(isscalar(checkpoint) && size(fit.theta,2) == 201 && ...
            isequal(fit.checkpointTheta(:,checkpoint),fit.theta(:,201)), ...
            'study2:FigureFit','Expected the common archived 200-transition fit.');
        saved = load(fullfile(resultsDir,'evaluation',[char(ids(j)),'.mat']),'evaluations');
        for k = 1:3
            evaluation = saved.evaluations([saved.evaluations.evaluationRange] == block.evaluationRange(k));
            assert(isscalar(evaluation) && isequal(evaluation.fitSteps,cfg.fitSteps), ...
                'study2:FigureFit','Evaluation must use the shared fit checkpoints.');
            errors = evaluation.oneStepErrors(:,checkpoint);
            assert(numel(errors) == 600 && all(isfinite(errors)) && ...
                abs(sqrt(mean(errors.^2))-block.predictionRMS(k)) < 1e-14, ...
                'study2:FigureScore','Prediction table disagrees with saved errors.');
            rows = [rows;score_row("a",ids(j),names(j),"evaluationRange", ...
                block.evaluationRange(k),"predictionRMS",block.predictionRMS(k), ...
                200,"held-out",600)]; %#ok<AGROW>
        end
    end
    block = sortrows(tracking(tracking.model == ids(j) & ...
        tracking.kind == "amplitude" & tracking.window == "principal",:),'amplitude');
    assert(height(block) == 3 && isequal(block.amplitude,[.2;.6;1]) && ...
        all(block.completed == 1 & block.expectedSamples == 600 & block.scoredSamples == 600), ...
        'study2:FigureTrackingData','Expected three complete principal-window scores.');
    for k = 1:3
        saved = load(fullfile(resultsDir,'runs',sprintf('amplitude_%02d_%s.mat',k,ids(j))),'result');
        r = saved.result;
        samples = find(r.time(1:r.nSteps) >= 20 & r.time(1:r.nSteps) < 80);
        assert(r.completed && r.nSteps == 800 && r.amplitude == block.amplitude(k) && ...
            isequal(samples,201:800) && numel(samples) == 600, ...
            'study2:FigureWindow','Principal must mean 20 <= t < 80 s, with 600 samples.');
        error = r.x(samples)-r.r(samples);
        assert(abs(sqrt(mean(error.^2))-block.trackingRMS(k)) < 1e-14, ...
            'study2:FigureScore','Tracking table disagrees with the archived principal window.');
        rows = [rows;score_row("b",ids(j),names(j),"amplitude", ...
            block.amplitude(k),"trackingRMS",block.trackingRMS(k), ...
            NaN,"20 <= t < 80 s",600)]; %#ok<AGROW>
    end
end
values = struct2table(rows);
assert(height(values) == 33 && all(isfinite(values.metricValue) & values.metricValue > 0), ...
    'study2:FigureScore','All plotted values must be finite and positive.');
end

function row = score_row(panel,id,name,variable,x,metric,y,fit,window,count)
row = struct('panel',panel,'model',name,'modelId',id, ...
    'horizontalVariable',variable,'horizontalValue',x, ...
    'metric',metric,'metricValue',y,'fittingTransitions',fit, ...
    'window',window,'scoredSamples',count);
end
