function values = study4_figure_data(resultsDir)
%STUDY4_FIGURE_DATA Exact archived coefficients and common-grid RMSE only.
% Retain 45 <= t <= 120, with no synthesized endpoint or new evaluation.
% Segment 2 starts at the 50 s grid snapshot, breaking the 49-to-50 s line.
saved = load(fullfile(resultsDir,'settings.mat'),'cfg'); cfg = saved.cfg;
assert(strcmp(cfg.campaign,'pilot') && cfg.measurementSigma == 0 && ...
    cfg.processSigma == 0 && cfg.Ts == .1 && cfg.K == 1200, ...
    'study4:FigureSource','Expected the saved deterministic 120 s pilot.');
grid = readtable(fullfile(resultsDir,'tables','grid.csv'),'TextType','string');
scenarios = ["represented","unrepresented"];
ids = ["A","Aplus","P2"];
names = ["Affine","Augmented affine","Complete quadratic"];
values = table;
for scenario = scenarios
    trueH = []; time = [];
    for m = 2:3
        saved = load(fullfile(resultsDir,'runs',sprintf('%s_%s.mat',scenario,ids(m))),'result');
        r = saved.result;
        ordering = ["d","a","b","q_xx"];
        if m == 3, ordering = [ordering,"q_xu","q_uu"]; end
        assert(strcmp(r.id,ids(m)) && strcmp(r.scenario,scenario) && ...
            r.completed && r.nSteps == 1200 && r.Ts == .1 && ...
            isequal(string(r.labels),ordering) && size(r.theta,2) == 1200 && ...
            size(r.theta,1) == numel(ordering),'study4:CoefficientOrdering', ...
            'Expected the complete saved coefficient ordering and history.');
        index = find(string(r.labels) == "q_xx");
        assert(isscalar(index) && index == 4,'study4:CoefficientOrdering','q_xx must be the fourth saved coefficient.');
        currentTime = r.time(1:size(r.theta,2));
        if isempty(time), time = currentTime; trueH = r.trueH;
        else
            assert(isequal(time,currentTime) && isequal(trueH,r.trueH), ...
                'study4:FigurePairing','The coefficient histories must share their recorded times and plant schedule.');
        end
        selected = currentTime >= 45 & currentTime <= 120;
        assert(isequal(find(selected),451:1200),'study4:FigureWindow', ...
            'Retain every saved coefficient from 45 through 119.9 s.');
        values = [values;rows(scenario,names(m),currentTime(selected), ...
            "Estimated xi^2 coefficient",r.theta(index,selected),ones(1,nnz(selected)))]; %#ok<AGROW>
    end
    if scenario == "represented"
        assert(isequal(trueH,.08*double(time >= 50)), ...
            'study4:TrueCoefficient','The archived represented change must be zero before 50 s and 0.08 afterward.');
        selected = time >= 45 & time <= 120;
        values = [values;rows(scenario,"True coefficient",time(selected), ...
            "True xi^2 coefficient",trueH(selected),ones(1,nnz(selected)))]; %#ok<AGROW>
    end
    for m = 1:3
        saved = load(fullfile(resultsDir,'evaluation',sprintf('%s_%s.mat',scenario,ids(m))),'evaluation');
        e = saved.evaluation;
        [x,u] = ndgrid(linspace(-1,1,21),linspace(-.7,.7,21));
        assert(strcmp(e.id,ids(m)) && strcmp(e.scenario,scenario) && ...
            isequal(e.time,0:119) && isequal(e.sampleIndices,0:10:1190) && ...
            all(e.attempted & e.valid) && isequal(e.x,x(:)) && isequal(e.u,u(:)) && ...
            all(isfinite(e.rms) & e.rms >= 0),'study4:GridSource', ...
            'Expected 120 valid one-second snapshots on the prescribed 441-point grid.');
        check = sortrows(grid(grid.scenarioId == scenario & grid.modelId == ids(m),:),'timeSeconds');
        assert(height(check) == 120 && isequal(check.timeSeconds,e.time.') && ...
            isequal(check.sampleIndex,e.sampleIndices.') && all(check.queryCount == 441) && ...
            all(check.attempted & check.valid & check.completed) && ...
            all(abs(check.predictionRMS-e.rms.') <= 8e-15*max(abs(e.rms.'),realmin)), ...
            'study4:GridCrosscheck','Saved evaluation.rms must agree with tables/grid.csv at its CSV precision.');
        selected = e.time >= 45 & e.time <= 120;
        values = [values;rows(scenario,names(m),e.time(selected), ...
            "Common-grid prediction RMSE",e.rms(selected),1+double(e.time(selected) >= 50))]; %#ok<AGROW>
    end
    known = grid(grid.scenarioId == scenario & grid.modelId == "K",:);
    assert(height(known) == 120 && all(known.predictionRMS == 0), ...
        'study4:KnownGridError','The omitted known-model grid error must be zero.');
end
assert(height(values) == 4200 && all(isfinite(values.value)), ...
    'study4:FigureValues','Expected 3,750 coefficient values and 450 grid errors.');
end
function block = rows(scenario,model,time,quantity,value,segment)
count = numel(time);
block = table(repmat(scenario,count,1),repmat(model,count,1),time(:), ...
    repmat(quantity,count,1),value(:),segment(:),'VariableNames', ...
    {'scenario','model','timeSeconds','quantity','value','segment'});
end
