function proof=ejc_measured_parent_check(a,r,cfg)
%EJC_MEASURED_PARENT_CHECK Read saved arrays only; retain original identities.
assert(isequal(a.snapshotIndices,cfg.anchors) && isequal(a.horizons,cfg.horizons) && ...
    isequal(a.inputModes,{'held','recordedRateLimited'}),'ejc:ClaimQueries','Measured query definitions differ.');
assert(isequal(a.campaign,r.campaign) && isequal(a.id,r.id) && a.trial==r.trial && ...
    any(string(a.id)==["A","S","W","R","P2","K"]),'ejc:ClaimParents','Audit/run identity differs.');
j=cfg.anchors+1;
assert(all(j+max(cfg.horizons)-1<=r.nSteps) && ...
    isequal(a.trueInitialState,r.x(j)) && isequal(a.measuredInitialState,r.y(j)) && ...
    isequal(a.snapshotTheta,r.theta(:,j)) && all(isfinite(r.u)), ...
    'ejc:ClaimSnapshots','Saved measured state/parameter/input links differ.');
shape=[numel(cfg.anchors),numel(cfg.horizons),2];
assert(isequal(size(a.valid),shape) && all(a.valid,'all') && a.allQueriesValid && ...
    a.invalidQueryCount==0 && a.checkedQueryCount==prod(shape) && isempty(a.failures), ...
    'ejc:ClaimValidity','Every prescribed measured query must be valid.');
names=["measuredModelError","freezingError","totalError","crossTerm","cleanModelError","initializationEffect"];
for name=names
    assert(isequal(size(a.(name)),shape) && all(isfinite(a.(name)),'all'), ...
        'ejc:ClaimValidity','Missing/nonfinite measured error.');
end
em=a.measuredModelError;ef=a.freezingError;et=a.totalError;ec=a.cleanModelError;ei=a.initializationEffect;
scale=max([1;abs(em(:));abs(ef(:));abs(et(:));abs(ec(:));abs(ei(:))]);
assert(isequal(a.crossTerm,2*em.*ef) && ...
    isequal(a.identityResidual,abs(et-em-ef)) && ...
    isequal(a.squaredIdentityResidual,abs(et.^2-em.^2-ef.^2-a.crossTerm)) && ...
    isequal(a.initializationIdentityResidual,abs(em-ec-ei)), ...
    'ejc:ClaimDecomposition','Saved decomposition differs from its own arrays.');
assert(max(a.identityResidual,[],'all')<=1e-11*scale && ...
    max(a.squaredIdentityResidual,[],'all')<=1e-11*scale^2 && ...
    max(a.initializationIdentityResidual,[],'all')<=1e-11*scale, ...
    'ejc:ClaimDecomposition','Original measured identities failed.');
assert(max(abs(ef(:,1,:)),[],'all')<=1e-11,'ejc:ClaimIdentity','Original first-step contact failed.');
if string(a.id)=="A",assert(max(abs(ef),[],'all')<=1e-11,'ejc:ClaimIdentity','Original affine identity failed.');end
if a.trial==0,assert(all(ei==0,'all'),'ejc:ClaimIdentity','Noiseless initialization identity failed.');end
proof=struct('passed',true,'model',string(a.id),'campaign',string(a.campaign),'trial',a.trial, ...
    'horizons',a.horizons,'inputModes',string(a.inputModes),'queryCount',numel(cfg.anchors), ...
    'maxAbsFreezing',squeeze(max(abs(ef),[],1)),'freezingRMS',squeeze(sqrt(mean(ef.^2,1))), ...
    'meanCrossTerm',squeeze(mean(a.crossTerm,1)),'identityLimit',1e-11, ...
    'snapshotLinksPassed',true,'validityPassed',true,'decompositionPassed',true);
end
