function out=ejc_qp_max_locator(a,b,rowA,rowB,c,pair,reduction)
%EJC_QP_MAX_LOCATOR Bind F0698 only to its real saved runs and claim map.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
p=jsondecode(fileread(fullfile(root,'studies/p07/p07_acceptance_policy.json')));
amend=p.maximum_locator_amendment;file=fullfile(root,amend.scope_map);
assert(strcmp(ejc_file_sha256(file),amend.scope_map_sha256),'ejc:LocatorIntegrity','Locator scope map changed.');
scope=jsondecode(fileread(file));
assert(c.study==string(scope.study) && c.file==string(scope.file) && scope.coverageId=="F0698" && ...
    scope.field=="qpConditionMax" && scope.maximumLocationClaim=="NOT_ASSERTED", ...
    'ejc:LocatorScope','Missing or contradictory passive locator scope.');
ejc_claim_source_guard(root,jsondecode(fileread(fullfile(root,amend.source_definitions))));
keys={'model','modelName','estimatedCoefficients','kind','amplitude','completed','attemptedSteps','terminationReason'};
assert(all(ismember(keys,rowA.Properties.VariableNames)) && all(ismember(keys,rowB.Properties.VariableNames)), ...
    'ejc:LocatorIdentity','Missing exact source keys.');
for side=1:2
    r=a;row=rowA;package=c.sources;if side==2,r=b;row=rowB;package=c.references;end
    source=ejc_table_run_source("study2",row,package);z=load(source,'result');
    assert(isequaln(z.result,r) && string(r.id)==row.model && string(r.kind)==row.kind && ...
        isequaln(r.amplitude,row.amplitude) && isequal(r.nSteps,row.attemptedSteps) && ...
        isequal(r.completed,row.completed),'ejc:LocatorIdentity','Broken own row/run source link.');
end
% The stored view is a CSV, not another unrounded maximum. Its own-history
% link uses only the already approved P13 encoding budget, never P6 slack.
assert(isfinite(rowA.qpConditionMax) && isfinite(rowB.qpConditionMax) && ...
    abs(rowA.qpConditionMax-reduction.sourceCurrent)<=ejc_csv_encoding_budget(reduction.sourceCurrent) && ...
    abs(rowB.qpConditionMax-reduction.sourceReference)<=ejc_csv_encoding_budget(reduction.sourceReference), ...
    'ejc:LocatorOwnCSV','Stored maximum does not encode its own exact history maximum.');
proof=struct('coverageId',"F0698",'maximumLocationClaim',"NOT_ASSERTED",'activeIndex',false,'exactAlias',false, ...
    'claimMap',string(amend.scope_map),'claimMapSHA256',string(amend.scope_map_sha256), ...
    'oldCandidate',string(amend.failed_candidate),'oldPolicySHA256',string(amend.failed_policy_sha256), ...
    'selectionCurrent',reduction.selectedCurrent,'selectionReference',reduction.selectedReference, ...
    'countCurrent',a.nSteps,'countReference',b.nSteps,'keysCurrent',rowA(:,keys),'keysReference',rowB(:,keys), ...
    'timeCurrent',a.time,'timeReference',b.time,'settingsCurrent',a.controlSettings,'settingsReference',b.controlSettings, ...
    'units',"dimensionless QP condition",'parentPassed',pair.passed,'hessianCount',pair.hessianCount,'ownSourcePassed',true, ...
    'sourceSHA256',c.sourceSHA256,'referenceSHA256',c.referenceSHA256, ...
    'ownMaximumCurrent',reduction.sourceCurrent,'ownMaximumReference',reduction.sourceReference, ...
    'ownIndexCurrent',reduction.argmaxCurrent,'ownIndexReference',reduction.argmaxReference);
proof.storedCSVCurrent=rowA.qpConditionMax;proof.storedCSVReference=rowB.qpConditionMax;
proof.ownCSVEncodingPassed=true;
proof.witnessIndices=unique([reduction.argmaxCurrent reduction.argmaxReference]);
proof.hessians=cell(numel(proof.witnessIndices),2);
for k=1:numel(proof.witnessIndices)
    j=proof.witnessIndices(k);
    for side=1:2
        r=a;if side==2,r=b;end
        qp=assemble_qp(r.A(j),r.B(j),r.c(j),1,r.y(j),r.u(j),zeros(1,size(r.plannedOutput,1)),r.controlSettings);
        proof.hessians{k,side}=qp.H;
    end
end
out=ejc_maximum_locator(a.qpCondition(1:a.nSteps),b.qpCondition(1:b.nSteps),proof);
if isfield(pair,'matrixEvidenceFile'),out.matrixEvidenceFile=pair.matrixEvidenceFile;out.matrixEvidenceSHA256=pair.matrixEvidenceSHA256;end
end
