function meta = study6_meta(kind,study,plant,id,name,unit,source,range)
%STUDY6_META Provenance travels with each saved numerical comparison.
meta = struct('kind',string(kind),'sourceStudy',study,'plant',string(plant), ...
    'modelId',string(id),'model',string(name),'unit',string(unit), ...
    'sourceFile',string(source),'sourceCampaign',"pilot",'trial',0, ...
    'scenario',"stationary",'evaluationRange',range,'status',"derived pilot", ...
    'fitSteps',NaN,'snapshotTimes',NaN,'snapshotLabels',{{'saved online snapshots'}});
end
