function [history,summary] = study6_constraints(output,root,cfg)
%STUDY6_CONSTRAINTS Reuse all four approved deterministic Plant B audit runs.
folder = study6_source(root,cfg,2);
saved = load(fullfile(folder,'settings.mat'),'cfg'); expected = saved.cfg.control; expected.hy = [.85;.85];
history = table; summary = table; runs = cell(1,4); ids = ["A","O3","E","K"];
for m = 1:4
    id = ids(m); filename = "runs/constraint_"+id+".mat";
    saved = load(fullfile(folder,filename),'result'); r = saved.result; runs{m} = r;
    [~,name] = study6_model('B',id);
    assert(strcmp(r.kind,'constraintAudit') && r.completed && r.nSteps == 100 && ...
        r.Ts == .1 && r.x(1) == 1.4 && r.u(1) == 0 && all(r.r == .6) && ...
        isequal(r.x,r.y) && isequal(r.controlSettings,expected));
    assert(max(abs(r.x(2:end)-study2_plant(r.x(1:end-1),r.u(1:end-1)))) <= cfg.tolerance);
    upper = max(r.x(2:end)-.85,0); lower = max(-r.x(2:end)-.85,0);
    predictedUpper = reshape(r.slack(1,1,:),1,[]); predictedLower = reshape(r.slack(2,1,:),1,[]);
    initial = abs(r.x(1))-.85;
    assert(abs(initial-.55) <= cfg.tolerance && abs(r.x(2)-.94) <= cfg.tolerance && abs(upper(1)-.09) <= cfg.tolerance);
    if id == "K"
        assert(abs(r.plannedOutput(1,1)-.94) <= cfg.tolerance && predictedUpper(1) >= .09-1e-7);
    end
    n = r.nSteps;
    block = table(repmat(string(name),n,1),repmat(id,n,1),(0:n-1).',r.time(1:n).', ...
        r.time(2:n+1).',r.plannedOutput(1,:).',predictedUpper.',predictedLower.', ...
        r.x(2:end).',upper.',lower.',max(upper,lower).',r.controlAccepted.', ...
        'VariableNames',{'model','modelId','originIndex','originTime','nextSampleTime', ...
        'firstPredictedOutput','predictedUpperSlack','predictedLowerSlack','actualNextOutput', ...
        'actualUpperViolation','actualLowerViolation','actualOutputViolation','controlAccepted'});
    history = [history;block]; %#ok<AGROW>
    row = struct('sourceStudy',2,'model',string(name),'sourceFile',cfg.sources{2}+"/"+filename, ...
        'unit',"dimensionless state",'attemptedSteps',n,'completed',r.completed, ...
        'initialViolation',initial,'firstActualFutureViolation',upper(1), ...
        'firstPredictedUpperSlack',predictedUpper(1),'firstPredictedLowerSlack',predictedLower(1), ...
        'maxSubsequentViolation',max(max(upper,lower)),'futureViolationSamples',nnz(max(upper,lower)>0), ...
        'newControlRuns',0);
    summary = [summary;struct2table(row)]; %#ok<AGROW>
end
save(fullfile(output,'constraint_audit.mat'),'runs','history','summary');
end
