function verdict=verification_study2_gram_reduction(a,b,row,reference,pair)
%VERIFICATION_STUDY2_GRAM_REDUCTION Check the specified Gram maximum using hash-bound saved sources.
assert(isstruct(pair) && pair.passed,'ejc:GramReportParents','Complete original paired parents must pass.');
assert(isrow(a.gramCount) && isrow(b.gramCount) && isequal(a.nSteps,b.nSteps) && ...
    isequal(a.gramCount,b.gramCount) && a.nSteps<=numel(a.gramCondition) && ...
    b.nSteps<=numel(b.gramCondition),'ejc:GramReportSelection','Invalid or changed full-window definition.');
ia=find(a.gramCount(1:a.nSteps)==50);ib=find(b.gramCount(1:b.nSteps)==50);
assert(~isempty(ia) && isequal(ia,ib),'ejc:GramReportSelection','Complete selected indices differ.');
assert(string(a.kind)=="amplitude" && string(b.kind)=="amplitude" && ...
    string(a.id)==row.model && string(b.id)==reference.model && row.model==reference.model && ...
    isequal(a.amplitude,row.amplitude) && isequal(b.amplitude,reference.amplitude) && ...
    isequal(a.amplitude,b.amplitude) && isequal(a.time,b.time) && ...
    a.nEstimated==row.parameterCount && b.nEstimated==reference.coefficients && ...
    a.nEstimated==b.nEstimated && a.nEstimated>0 && a.completed && b.completed && row.runCompleted && ...
    row.recordedFullWindowCount==numel(ia) && row.validFullWindowCount==numel(ia) && ...
    reference.fullWindows==numel(ib) && row.invalidFullWindowCount==0 && ...
    row.relativeThreshold==1e-10 && reference.relative_singular_value_threshold==1e-10, ...
    'ejc:GramReportIdentity','Source identity, completion, dimensions or original report facts differ.');
ha=a.gramCondition(ia);hb=b.gramCondition(ib);
assert(isa(ha,'double') && isa(hb,'double') && isreal(ha) && isreal(hb) && ...
    ~any(isnan(ha)) && ~any(isnan(hb)),'ejc:GramReportSource','Invalid raw condition history.');
[ma,ka]=max(ha);[mb,kb]=max(hb);
assert(isequaln(ma,row.maxStoredCondition),'ejc:GramReportOwnReduction','Current scalar is not its own exact maximum.');
ownReference=isequal(mb,reference.maxStoredCondition) || ...
    (isfinite(mb) && isfinite(reference.maxStoredCondition) && ...
    abs(mb-reference.maxStoredCondition)<=32*eps(max(1,abs(reference.maxStoredCondition))));
assert(ownReference,'ejc:GramReportOwnReduction','Historical CSV differs from its own MAT maximum under the original source contract.');
selected=pair.gramRows(ismember([pair.gramRows.index],ia));
assert(isequal([selected.index],ia) && all([selected.eligibleToAdvance]) && ...
    isequaln([selected.rawCurrent],ha) && isequaln([selected.rawReference],hb), ...
    'ejc:GramReportParents','Missing, stale or wrong selected F0533 parent evidence.');
v=verification_gram_reduce(ma,reference.maxStoredCondition,ia,ib,selected,true);
assert(v.eligibleToAdvance,'ejc:GramReportNumerical','%s',v.reason);
verdict=v;verdict.passed=v.eligibleToAdvance;verdict.binding="P07_STUDY2_GRAM_MAX_V1";
verdict.ownSourcePassed=true;verdict.parentsPassed=true;verdict.parentScope="F0533";
verdict.selectionCurrent=ia;verdict.selectionReference=ib;
verdict.maximumCurrent=ma;verdict.maximumReference=mb;
verdict.firstCurrent=ia(ka);verdict.firstReference=ib(kb);
verdict.exactMaximizersCurrent=ia(ha==ma);verdict.exactMaximizersReference=ib(hb==mb);
verdict.witnessIndices=unique([ia(ka) ib(kb)]);
verdict.witnessParents=selected(ismember([selected.index],verdict.witnessIndices));
verdict.selectedParentChecks=numel(selected);verdict.qualifiedParentChecks=sum([selected.qualifiedCount]);
verdict.ordinaryP6=verification_acceptance_numeric(ma,reference.maxStoredCondition,1e-8,1e-7,true);
verdict.noCrossRunLocatorClaim=true;verdict.model=row.model;verdict.amplitude=row.amplitude;
end
