function evidence=verification_settings_namespace(a,b,rule,context,quantity,namesA,namesB)
%VERIFICATION_SETTINGS_NAMESPACE Only the outer F2710 MAT-variable namespace.
evidence=struct('applied',false);
if ~(context.study=="study6" && context.file=="settings.mat" && ...
        string(rule.coverage_id)=="F2710" && quantity=="value"),return;end
assert(isstruct(a) && isscalar(a) && isstruct(b) && isscalar(b), ...
    'ejc:SettingsNamespace','Outer settings namespace must be a scalar struct.');
expected=["cfg";"sources"];
assert(numel(namesA)==2 && numel(namesB)==2 && ...
    all(ismember(expected,namesA)) && all(ismember(expected,namesB)), ...
    'ejc:SettingsNamespace','Exact retained namespace {cfg,sources} required.');
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
p=jsondecode(fileread(fullfile(root,'verification/specification/numerical_policy.json')));
assert(isfield(p,'settings_namespace_amendment') && ...
    strcmp(p.settings_namespace_amendment.coverage_id,'F2710'), ...
    'ejc:SettingsNamespacePolicy','Missing scoped B1 policy binding.');
evidence=struct('applied',true,'scope',"F2710:study6/settings.mat:value", ...
    'ruleVersion',string(p.settings_namespace_amendment.version), ...
    'rawCurrentOrder',{fieldnames(a)},'rawReferenceOrder',{fieldnames(b)}, ...
    'retainedCurrentOrder',namesA,'retainedReferenceOrder',namesB, ...
    'exactRetainedNames',expected,'comparisonTraversal',expected, ...
    'descendantChecksStillRequired',true);
evidence.currentSources=verification_settings_source_binding(a,context.sources);
evidence.referenceSources=verification_settings_source_binding(b,context.references);
end
