function scores = study5_metrics(r,cfg)
%STUDY5_METRICS Appendix A half-open windows; terminal input is unapplied.
rows = struct([]); time = r.time(1:end-1);
for w = 1:2
    mask = time >= cfg.windows(w,1) & time < cfg.windows(w,2);
    indices = find(mask & (1:numel(time)) <= r.nSteps);
    duIndices = indices(indices > 1); du = r.u(duIndices)-r.u(duIndices-1);
    error = r.x(indices)-r.r(indices); prediction = r.prediction(indices)-r.x(indices+1);
    row = struct('model',string(r.name),'modelId',string(r.id),'coefficientCount',r.nEstimated, ...
        'window',string(cfg.windowNames{w}),'windowStart',cfg.windows(w,1),'windowEnd',cfg.windows(w,2), ...
        'completed',r.completed,'status',"complete",'expectedSamples',nnz(mask),'scoredSamples',numel(indices), ...
        'incrementSamples',numel(du),'trackingRMS',score_rms(error),'peakTrackingError',peak(abs(error)), ...
        'inputRMS',score_rms(r.u(indices)),'meanAbsoluteIncrement',score_mean(abs(du)), ...
        'totalInputVariation',sum(abs(du)),'predictionTrueRMS',score_rms(prediction), ...
        'predictionMeasuredRMS',score_rms(r.prediction(indices)-r.y(indices+1)), ...
        'predictionFinite',nnz(isfinite(prediction)),'stateMin',low(r.x(indices)), ...
        'stateMax',peak(r.x(indices)),'inputMin',low(r.u(indices)),'inputMax',peak(r.u(indices)), ...
        'outputViolationPeak',peak(max(abs(r.x(indices))-cfg.control.hy(1),0)), ...
        'outputViolationCount',nnz(abs(r.x(indices)) > cfg.control.hy(1)), ...
        'inputViolationPeak',peak(max(abs(r.u(indices))-cfg.control.hu(1),0)), ...
        'incrementViolationPeak',peak(max(abs(du)-cfg.control.hdu(1),0)));
    if ~r.completed, row.status = "incompletePrefix"; end
    rows = [rows;row]; %#ok<AGROW>
end
scores = struct2table(rows);
end
function value = score_mean(x)
value = NaN; if ~isempty(x) && all(isfinite(x),'all'), value = mean(x,'all'); end
end
function value = score_rms(x)
value = sqrt(score_mean(x.^2));
end
function value = peak(x)
value = NaN; if ~isempty(x) && all(isfinite(x),'all'), value = max(x,[],'all'); end
end
function value = low(x)
value = NaN; if ~isempty(x) && all(isfinite(x),'all'), value = min(x,[],'all'); end
end
