function values = study5_figure_data(resultsDir)
%STUDY5_FIGURE_DATA Exact source-table values, checked against saved arrays.
% This reader never propagates a model, fits parameters, or runs control.
saved = load(fullfile(resultsDir,'settings.mat'),'cfg'); cfg = saved.cfg;
assert(strcmp(cfg.campaign,'deterministic pilot') && cfg.Ts == .1 && ...
    cfg.measurementSigma == 0 && cfg.processSigma == 0, ...
    'study5:FigureSource','Expected the saved deterministic Plant C pilot.');
quadrature = sortrows(readtable(fullfile(resultsDir,'tables','quadrature.csv')),'Ts');
saved = load(fullfile(resultsDir,'evaluation','numerical_audit.mat'),'audit'); audit = saved.audit;
assert(isequal(quadrature.Ts,[.025;.05;.1]) && all(quadrature.queries == 441));
assert(isequal(size(audit.trapezoidResidual),[441 3]));
values = table;
columns = ["trapezoidResidualRMS_Nm","trapezoidResidualMax_Nm"];
statistics = ["RMS","Maximum"];
for statistic = 1:2
    for j = 1:3
        s = find(audit.sampling == quadrature.Ts(j)); assert(isscalar(s));
        residual = audit.trapezoidResidual(:,s); % Already divided by Ts.
        check = sqrt(mean(residual.^2));
        if statistic == 2, check = max(abs(residual)); end
        csv_matches(quadrature.(columns(statistic))(j),check);
    end
    values = [values;rows("a",statistics(statistic),"Sampling interval Ts", ...
        quadrature.Ts,"Normalized endpoint-quadrature residual", ...
        quadrature.(columns(statistic)),"N m",columns(statistic),0,"offline audit",441)]; %#ok<AGROW>
end

tableData = readtable(fullfile(resultsDir,'tables','forecasts.csv'),'TextType','string');
saved = load(fullfile(resultsDir,'evaluation','common_queries.mat'),'queries'); q = saved.queries;
saved = load(fullfile(resultsDir,'records.mat'),'records'); record = saved.records.evaluation;
assert(isequal(q.anchors,20:20:580) && isequal(q.horizons,[1 2 5 10 20]) && ...
    isequal(q.inputModes,{'held','rateLimited'}) && isequal(size(q.truth),[29 21 2]) && ...
    q.referenceSubsteps == 40 && isequal(q.initialStates,record.x(q.anchors+1)), ...
    'study5:ForecastQueries','Expected 29 common initial states and the saved refined reference.');
for a = 1:29
    index = q.anchors(a)+1;
    assert(isequal(q.inputs(a,:,2),record.u(index:index+19)) && ...
        all(abs(diff(q.inputs(a,:,2))) <= .1+eps), ...
        'study5:ForecastInputs','Saved rate-limited sequences must match the independent record.');
end
ids = ["I","D","A","P3","K"];
names = ["Integrated physical","Euler-informed direct","Affine","Complete cubic","Known-model reference"];
for m = 1:5
    block = sortrows(tableData(tableData.modelId == ids(m) & ...
        tableData.fittingTransitions == 200 & tableData.inputMode == "rateLimited",:),'horizon');
    assert(height(block) == 5 && isequal(block.horizon,[1;2;5;10;20]) && ...
        all(block.queryCount == 29 & block.validQueries == 29) && all(block.model == names(m)), ...
        'study5:ForecastSelection','Use all five 200-transition rate-limited nonlinear forecast scores.');
    saved = load(fullfile(resultsDir,'evaluation',ids(m)+".mat"),'forecasts'); f = saved.forecasts;
    saved = load(fullfile(resultsDir,'fits',"fit_"+ids(m)+".mat"),'fit'); fit = saved.fit;
    assert(strcmp(f.id,ids(m)) && isequal(f.anchors,q.anchors) && ...
        isequal(f.horizons,q.horizons) && isequal(f.inputModes,q.inputModes) && ...
        isequal(f.fitSteps,[25 50 100 200]) && isequal(f.frozenTheta,fit.mappedTheta(:,201)) && ...
        isequal(f.states(:,1,2),q.initialStates.') && all(f.valid(:,:,2),'all'), ...
        'study5:FrozenForecast','Forecasts must use the common queries and final initialized snapshot.');
    errors = f.states(:,q.horizons+1,2)-q.truth(:,q.horizons+1,2);
    assert(isequal(errors,f.modelError(:,:,2)),'study5:NonlinearForecast', ...
        'Saved errors must be differences of the nonlinear trajectories and common reference.');
    csv_matches(block.predictionRMS,sqrt(mean(errors.^2,1)).');
    if m == 5
        assert(isequal(errors,q.knownNumericalError(:,q.horizons+1,2)) && ...
            all(block.predictionRMS > 0),'study5:KnownNumericalError', ...
            'The omitted known-model error is a saved nonzero propagation discrepancy.');
        continue;
    end
    values = [values;rows("b",names(m),"Forecast horizon H Ts", ...
        block.horizon*cfg.Ts,"Nonlinear prediction RMSE",block.predictionRMS, ...
        "rad/s","predictionRMS",200,"rateLimited",29)]; %#ok<AGROW>
end
assert(height(values) == 26 && all(isfinite(values.value) & values.value > 0));
end
function csv_matches(actual,expected)
assert(isequal(size(actual),size(expected)) && ...
    all(abs(actual-expected) <= 8e-15*max(abs(expected),realmin),'all'), ...
    'study5:FigureCrosscheck','Source CSV must agree with the saved arrays at its CSV precision.');
end
function block = rows(panel,series,horizontal,x,quantity,y,unit,column,fit,mode,queries)
n = numel(x);
block = table(repmat(panel,n,1),repmat(series,n,1),repmat(horizontal,n,1),x(:), ...
    repmat("s",n,1),repmat(quantity,n,1),y(:),repmat(unit,n,1),repmat(column,n,1), ...
    repmat(fit,n,1),repmat(mode,n,1),repmat(queries,n,1),'VariableNames', ...
    {'panel','series','horizontalVariable','horizontalValue','horizontalUnit', ...
    'quantity','value','unit','sourceColumn','fittingTransitions','inputMode','queryCount'});
end
